#!/usr/bin/env sh
export SNIP_PATH=$(dirname 'readlink -f $0')

export NODE_PATH=\
$NODE_PATH\
:$SNIP_PATH\
:$SNIP_PATH/dependencies/redis-node-client/lib\
:$SNIP_PATH/dependencies/nerve/lib\
:$SNIP_PATH/dependencies/ #underscore.js

node "$@"
